---
# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: en
caseSensitive: false
allowCompoundWords: true
ignoreRandomStrings: true
useGitignore: true
dictionaries:
  - softwareTerms
  - node
  - npm
  - html
  - python
  - bash
  - golang
  - coding-compound-terms
  - computing-acronyms
  - filetypes
  - software-tools
  - softwareTerms
  - k8s
ignorePaths:
  - CHANGELOG.md
  - .vscode/**
patterns:
  - name: markdown-fenced-code-blocks
    pattern: /^\s*(`{3,}|~{3,}).*[\s\S]*?^\s*\1/gm
overrides:
  - filename:
      - "**/*.md"
    ignoreRegExpList:
      - markdown-fenced-code-blocks
words:
  - apeiros
  - gofmt
  - oxfmt
  - zizmor
  - zizmorcore
