# yamllint disable rule:quoted-strings
---
default: true
gitignore: true
code-block-style:
  style: fenced
emphasis-style: false
header-style:
  style: atx
hr-style:
  style: "---"
line-length:
  line_length: 1800
  headings: true
  heading_line_length: 100
  tables: false
no-duplicate-heading:
  siblings_only: true
no-emphasis-as-heading: false
no-inline-html: false
no-trailing-punctuation:
  punctuation: .,;:!。，；：！
no-trailing-spaces: false
ol-prefix: false
reference-links-images: false
table-column-style: false
no-multiple-blanks: false
no-bare-urls: false
MD025: false
MD055: false
MD056: false
MD059: false
proper-names:
  code_blocks: false
  html_elements: false
  names:
    - DevOps
