#!/usr/bin/env bash

set -euo pipefail

failed=0

for file in "$@"; do
  [[ -f "$file" ]] || continue

  devskim analyze \
    -I "$file" \
    --options-json .devskim.json \
    -f text \
    -E \
    --skip-git-ignored-files \
    --skip-excerpts ||
    failed=1
done

exit "$failed"
