#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=../lib/common.sh
source "$(dirname -- "$0")/../lib/common.sh"

common_root="$(common_remote_root)"

if has_shellcheck_config; then
  exec mise x -- shellcheck "$@"
fi

exec mise x -- \
  shellcheck \
  --rcfile "$common_root/.shellcheckrc" \
  "$@"
