#!/usr/bin/env python3
"""Render shared Mise requirements using Lefthook's native configuration loader."""

import argparse
import copy
import hashlib
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

import tomllib

MARKER = "# Generated by common tools:sync. Do not edit."
TAG_PREFIX = "common-tools:"
OUTPUT = Path(".mise/conf.d/common.toml")
CATALOG = Path(__file__).resolve().parents[2] / "tools/catalog.toml"
# These are Lefthook 2.1's documented local configuration locations.
LOCAL_CONFIGS = {
    name + extension
    for name in ("lefthook-local", ".lefthook-local", ".config/lefthook-local")
    for extension in (".yml", ".yaml", ".json", ".jsonc", ".toml")
}


class ConfigurationError(Exception):
    """An input needs attention before generated configuration can be updated."""


def run(*args, cwd=None, env=None):
    result = subprocess.run(
        args, cwd=cwd, env=env, capture_output=True, text=True, check=False
    )
    if result.returncode:
        raise ConfigurationError(result.stderr.strip() or result.stdout.strip())
    return result.stdout


def team_configuration(root):
    """Hide untracked personal overrides in a temporary view without moving files.

    Only directory entries are linked: even a large consumer is not copied.
    The original Git directory keeps native remote resolution and linked Git
    worktrees working. `dump` reads configuration; it never executes hook jobs.
    """
    tracked = set(
        run("git", "ls-files", "-z", "--", *sorted(LOCAL_CONFIGS)).split("\0")
    )
    personal = LOCAL_CONFIGS - tracked
    git_dir = run("git", "rev-parse", "--absolute-git-dir").strip()
    with tempfile.TemporaryDirectory(prefix="common-tools-") as directory:
        view = Path(directory)

        def link_directory(source, destination, prefix=""):
            for path in source.iterdir():
                relative = prefix + path.name
                if relative == ".git" or relative in personal:
                    continue
                target = destination / path.name
                if relative == ".config" and path.is_dir():
                    target.mkdir()
                    link_directory(path, target, ".config/")
                else:
                    target.symlink_to(path, target_is_directory=path.is_dir())

        link_directory(root, view)
        env = {**os.environ, "GIT_DIR": git_dir, "GIT_WORK_TREE": str(view)}
        if override := env.get("LEFTHOOK_CONFIG"):
            config = Path(override)
            if config.is_absolute():
                try:
                    env["LEFTHOOK_CONFIG"] = str(view / config.relative_to(root))
                except ValueError as error:
                    raise ConfigurationError(
                        "LEFTHOOK_CONFIG must be inside the consuming repository"
                    ) from error
        return json.loads(
            run("lefthook", "dump", "--format", "json", cwd=view, env=env)
        )


def selected_groups(config):
    groups = {"base"}

    def walk(value):
        if isinstance(value, dict):
            for tag in value.get("tags", []):
                if isinstance(tag, str) and tag.startswith(TAG_PREFIX):
                    groups.add(tag.removeprefix(TAG_PREFIX))
            for child in value.values():
                walk(child)
        elif isinstance(value, list):
            for child in value:
                walk(child)

    # Selection determines dependencies. File filters and conditional skips
    # must not change the installed toolset from one commit or branch to another.
    walk(config)
    return groups


def merge_settings(target, source, path):
    for key, value in source.items():
        location = f"{path}.{key}"
        if key not in target:
            target[key] = copy.deepcopy(value)
        elif isinstance(value, dict) and isinstance(target[key], dict):
            merge_settings(target[key], value, location)
        elif target[key] != value:
            raise ConfigurationError(f"conflicting group settings for {location}")


def resolve(catalog, groups):
    if catalog.get("schema_version") != 1:
        raise ConfigurationError("unsupported tools/catalog.toml schema_version")
    tools = catalog.get("tools", {})
    definitions = catalog.get("groups", {})
    if not isinstance(tools, dict) or not isinstance(definitions, dict):
        raise ConfigurationError("catalog tools and groups must be TOML tables")
    result = {"tools": {}}

    def add_tool(name, parents=()):
        if name in parents:
            raise ConfigurationError(
                "cyclic tool dependency: " + " -> ".join((*parents, name))
            )
        if name not in tools:
            raise ConfigurationError(f"tool {name!r} has no catalog definition")
        if name in result["tools"]:
            return
        specification = tools[name]
        if isinstance(specification, dict):
            dependencies = specification.get("depends", [])
            if not isinstance(specification.get("version"), str):
                raise ConfigurationError(f"tool {name!r} needs a version string")
            if not isinstance(dependencies, list) or not all(
                isinstance(t, str) for t in dependencies
            ):
                raise ConfigurationError(
                    f"tool {name!r} needs a list of dependency names"
                )
            for dependency in dependencies:
                add_tool(dependency, (*parents, name))
        if not isinstance(specification, (str, dict)):
            raise ConfigurationError(f"invalid tool definition for {name!r}")
        result["tools"][name] = specification

    for name in sorted(groups):
        if name not in definitions:
            raise ConfigurationError(
                f"unknown tool group {name!r}; update the hook and catalog together"
            )
        group = definitions[name]
        if not isinstance(group, dict) or set(group) - {"tools", "env", "deps"}:
            raise ConfigurationError(f"invalid tool group {name!r}")
        requirements = group.get("tools", [])
        if not isinstance(requirements, list) or not all(
            isinstance(t, str) for t in requirements
        ):
            raise ConfigurationError(f"group {name!r} needs a list of tool names")
        for tool in requirements:
            add_tool(tool)
        for section in ("env", "deps"):
            if section in group:
                if not isinstance(group[section], dict):
                    raise ConfigurationError(
                        f"group {name!r} needs a table for {section}"
                    )
                merge_settings(result.setdefault(section, {}), group[section], section)
    return result


def toml_value(value):
    """Encode the catalog's strings, booleans, lists and inline tables as TOML."""
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, bool):
        return str(value).lower()
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(item) for item in value) + "]"
    if isinstance(value, dict):
        return (
            "{ "
            + ", ".join(
                f"{toml_value(key)} = {toml_value(item)}"
                for key, item in sorted(value.items())
            )
            + " }"
        )
    raise ConfigurationError(f"unsupported catalog value: {value!r}")


def render(configuration, header):
    lines = [*header, ""]
    for section, values in configuration.items():
        lines.append(f"[{section}]")
        lines.extend(
            f"{toml_value(key)} = {toml_value(value)}"
            for key, value in sorted(values.items())
        )
        lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail if common.toml is missing or stale"
    )
    args = parser.parse_args()
    root = Path(run("git", "rev-parse", "--show-toplevel").strip())
    os.chdir(root)
    catalog_text = CATALOG.read_text()
    catalog = tomllib.loads(catalog_text)
    groups = selected_groups(team_configuration(root))
    configuration = resolve(catalog, groups)
    header = [
        MARKER,
        "# Catalog SHA256: " + hashlib.sha256(catalog_text.encode()).hexdigest(),
        "# Groups: " + ", ".join(sorted(groups)),
    ]
    output = root / OUTPUT
    if output.is_symlink() or not output.resolve().is_relative_to(root):
        raise ConfigurationError(
            f"{OUTPUT} must be a regular file within the repository"
        )
    existing = output.read_text() if output.exists() else ""
    if existing and existing.splitlines()[0] != MARKER:
        raise ConfigurationError(
            f"{OUTPUT} is not generated; move its project settings into .mise/config.toml "
            "and remove the old file before syncing"
        )
    # Formatting is allowed: compare TOML values and provenance, not whitespace.
    current = (
        existing.splitlines()[:3] == header and tomllib.loads(existing) == configuration
    )
    if args.check:
        if not current:
            print(f"{OUTPUT} is stale; run mise run tools:sync", file=sys.stderr)
            return 1
        print(f"{OUTPUT} is current")
    elif current:
        print(f"{OUTPUT} is current")
    else:
        output.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile(
            mode="w", dir=output.parent, delete=False
        ) as temporary:
            temporary.write(render(configuration, header))
            temporary_path = Path(temporary.name)
        try:
            temporary_path.chmod(0o644)
            temporary_path.replace(output)
        finally:
            temporary_path.unlink(missing_ok=True)
        print(f"Generated {OUTPUT} ({len(configuration['tools'])} tools)")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (ConfigurationError, OSError, ValueError) as error:
        print(f"common tools: {error}", file=sys.stderr)
        sys.exit(1)
