---
name: PR title

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

  merge_group:
    types:
      - checks_requested

permissions:
  pull-requests: read

concurrency:
  group: pr-title-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  title:
    name: PR title
    uses: $/.github/workflows/pr-title-check.yaml
